import type { ApplicationContext } from "../context.js";
import { AppError } from "../errors.js";
import { getConfig } from "../config.js";
import { id, now, Repositories } from "../database/repositories.js";
import type { TranscriptionProgress, TranscriptionResult } from "./types.js";

const activeStatuses = ["queued", "preparing", "processing", "finalizing"];
export class TranscriptionService {
  constructor(private readonly repositories: Repositories) {}
  start(context: ApplicationContext, voiceMessageId: string, options: { language?: string; model?: string } = {}) {
    const message = this.repositories.getVoiceMessage(context, voiceMessageId);
    if (message.download_status !== "downloaded" || !message.local_file_path) throw new AppError("AUDIO_FILE_MISSING", "Download the voice message before starting transcription.");
    const active = this.repositories.sqlite.prepare(`SELECT id FROM transcription_jobs WHERE voice_message_id=? AND status IN (${activeStatuses.map(() => "?").join(",")})`).get(voiceMessageId, ...activeStatuses);
    if (active) throw new AppError("TRANSCRIPTION_ALREADY_ACTIVE", "A transcription is already active for this voice message.", 409);
    const jobId = id("tr"), timestamp = now(), model = options.model ?? getConfig().whisperModel;
    this.repositories.sqlite.transaction(() => {
      this.repositories.sqlite.prepare("INSERT INTO transcription_jobs(id,user_id,voice_message_id,provider,model,requested_language,status,progress_phase,progress_type,progress_percent,elapsed_milliseconds,queued_at,progress_updated_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(jobId, context.userId, voiceMessageId, "self_hosted_whisper", model, options.language ?? null, "queued", "queued", "indeterminate", 0, 0, timestamp, timestamp, timestamp, timestamp);
      this.repositories.sqlite.prepare("UPDATE voice_messages SET transcription_status='queued',updated_at=? WHERE id=? AND user_id=?").run(timestamp, voiceMessageId, context.userId);
    })();
    return this.repositories.getJob(context, jobId);
  }
  cancel(context: ApplicationContext, jobId: string) { const job = this.repositories.getJob(context, jobId); if (["completed","failed","cancelled"].includes(job.status)) return job; const timestamp = now(); this.repositories.sqlite.transaction(() => { this.repositories.sqlite.prepare("UPDATE transcription_jobs SET status='cancelled',progress_phase='cancelled',cancelled_at=?,updated_at=?,progress_updated_at=? WHERE id=? AND user_id=?").run(timestamp,timestamp,timestamp,jobId,context.userId); this.repositories.sqlite.prepare("UPDATE voice_messages SET transcription_status='cancelled',updated_at=? WHERE id=? AND user_id=?").run(timestamp,job.voiceMessageId,context.userId); })(); return this.repositories.getJob(context, jobId); }
  retry(context: ApplicationContext, jobId: string) { const job = this.repositories.getJob(context, jobId); if (!["failed","cancelled"].includes(job.status)) throw new AppError("VALIDATION_ERROR", "Only failed or cancelled transcriptions can be retried."); return this.start(context, job.voiceMessageId, { language: job.requestedLanguage, model: job.model }); }
  persistProgress(jobId: string, progress: TranscriptionProgress): void {
    const job = this.repositories.sqlite.prepare("SELECT user_id AS userId,voice_message_id AS voiceMessageId,status FROM transcription_jobs WHERE id=?").get(jobId) as any; if (!job || job.status === "cancelled") return;
    const status = ["preparing_audio", "loading_model"].includes(progress.phase) ? "preparing" : progress.phase === "transcribing" ? "processing" : progress.phase;
    this.repositories.sqlite.transaction(() => { this.repositories.sqlite.prepare("INSERT OR IGNORE INTO transcription_progress_events(id,user_id,transcription_job_id,sequence,phase,progress_type,percent,phase_percent,processed_audio_seconds,total_audio_seconds,estimated_remaining_seconds,elapsed_milliseconds,partial_text_delta,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id("evt"),job.userId,jobId,progress.sequence,progress.phase,progress.progressType,progress.percent ?? null,progress.phasePercent ?? null,progress.processedAudioSeconds ?? null,progress.totalAudioSeconds ?? null,progress.estimatedRemainingSeconds ?? null,progress.elapsedMilliseconds,progress.partialText ?? null,progress.updatedAt); this.repositories.sqlite.prepare("UPDATE transcription_jobs SET status=?,progress_phase=?,progress_type=?,progress_percent=?,phase_percent=?,processed_audio_seconds=?,total_audio_seconds=?,estimated_remaining_seconds=?,elapsed_milliseconds=?,partial_text=COALESCE(?,partial_text),progress_updated_at=?,heartbeat_at=?,updated_at=? WHERE id=? AND status!='cancelled'").run(status,progress.phase,progress.progressType,progress.percent ?? null,progress.phasePercent ?? null,progress.processedAudioSeconds ?? null,progress.totalAudioSeconds ?? null,progress.estimatedRemainingSeconds ?? null,progress.elapsedMilliseconds,progress.partialText ?? null,progress.updatedAt,progress.updatedAt,progress.updatedAt,jobId); this.repositories.sqlite.prepare("UPDATE voice_messages SET transcription_status=?,updated_at=? WHERE id=?").run(status,progress.updatedAt,job.voiceMessageId); })();
  }
  complete(jobId: string, result: TranscriptionResult): void { const job = this.repositories.sqlite.prepare("SELECT * FROM transcription_jobs WHERE id=?").get(jobId) as any; if (!job || job.status === "cancelled") return; const timestamp = now(); this.repositories.sqlite.transaction(() => { this.repositories.sqlite.prepare("INSERT INTO transcriptions(id,user_id,voice_message_id,transcription_job_id,provider,model,requested_language,detected_language,text,duration_milliseconds,audio_duration_seconds,real_time_factor,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id("tx"),job.user_id,job.voice_message_id,jobId,job.provider,result.model,job.requested_language,result.detectedLanguage ?? null,result.text,result.durationMilliseconds,result.audioDurationSeconds,result.realTimeFactor ?? null,timestamp,timestamp); this.repositories.sqlite.prepare("UPDATE transcription_jobs SET status='completed',progress_phase='completed',progress_type='exact',progress_percent=100,phase_percent=100,estimated_remaining_seconds=0,detected_language=?,completed_at=?,progress_updated_at=?,updated_at=? WHERE id=?").run(result.detectedLanguage ?? null,timestamp,timestamp,timestamp,jobId); this.repositories.sqlite.prepare("UPDATE voice_messages SET transcription_status='completed',updated_at=? WHERE id=?").run(timestamp,job.voice_message_id); })(); }
  fail(jobId: string, error: unknown): void { const timestamp=now(), message=error instanceof Error ? error.message.slice(0,500) : "Transcription failed."; const job=this.repositories.sqlite.prepare("SELECT voice_message_id AS voiceMessageId,status FROM transcription_jobs WHERE id=?").get(jobId) as any; if (!job || job.status === "cancelled") return; this.repositories.sqlite.transaction(()=>{ this.repositories.sqlite.prepare("UPDATE transcription_jobs SET status='failed',progress_phase='failed',error_code='TRANSCRIPTION_FAILED',error_message=?,failed_at=?,progress_updated_at=?,updated_at=? WHERE id=?").run(message,timestamp,timestamp,timestamp,jobId); this.repositories.sqlite.prepare("UPDATE voice_messages SET transcription_status='failed',updated_at=? WHERE id=?").run(timestamp,job.voiceMessageId); })(); }
}
